// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 The Photometoria contributors

//! Catalog data model
//!
//! This module defines the Catalog entity, which represents a Lightroom catalog
//! identity. Each catalog is uniquely identified by a UUID generated by the
//! Lightroom plugin and sent with every catalog-scoped API request.

use serde::{Deserialize, Serialize};
use uuid::Uuid;

// ============================================================================
// Catalog Entity (Internal Domain Model)
// ============================================================================

/// Represents a Lightroom catalog identity.
///
/// A Catalog groups tasks that belong to the same Lightroom catalog,
/// preventing cross-library mixing of photos and metadata. The UUID is
/// generated by the Lightroom plugin and stored in the catalog's plugin
/// preferences.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Catalog {
    /// Unique identifier generated by the Lightroom plugin
    pub catalog_id: Uuid,
}

impl Catalog {
    /// Creates a new Catalog with the given identifier.
    ///
    /// The `catalog_id` is expected to come from the Lightroom plugin,
    /// which generates it once per catalog and stores it persistently.
    ///
    /// # Arguments
    /// * `catalog_id` - UUID identifying the Lightroom catalog
    pub fn new(catalog_id: Uuid) -> Self {
        Self { catalog_id }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_catalog_new_stores_id() {
        let id = Uuid::new_v4();
        let catalog = Catalog::new(id);
        assert_eq!(catalog.catalog_id, id);
    }

    #[test]
    fn test_catalog_serialization_roundtrip() {
        let catalog = Catalog::new(Uuid::new_v4());
        let json = serde_json::to_string(&catalog).unwrap();
        let deserialized: Catalog = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.catalog_id, catalog.catalog_id);
    }

    #[test]
    fn test_catalog_deserialization() {
        let json = r#"{"catalog_id":"550e8400-e29b-41d4-a716-446655440000"}"#;
        let catalog: Catalog = serde_json::from_str(json).unwrap();
        assert_eq!(
            catalog.catalog_id,
            Uuid::parse_str("550e8400-e29b-41d4-a716-446655440000").unwrap()
        );
    }
}
